layout_spectrum: 1
typography_spectrum: 0.0477651
color:
  lightness: 0.4144032
  brandStrength: 1
  saturation: 0.7510638
  rhythmicContrast: 0.9761706
  brandColors:
    - '#050303'
    - '#87C7F2'
    - '#91A39A'
    - '#D7EBE0'
    - '#1E384C'
name: Kerala.nu
